FROM ubuntu:14.04

# Set debconf to run non-interactively
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# Install base dependencies
RUN apt-get update && apt-get install -y -q --no-install-recommends \
	git \
	ca-certificates \
        curl

# Install nvm with node and npm
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - \
    && apt-get install -y -q --no-install-recommends nodejs

RUN locale-gen en_US.UTF-8
ENV LANG       en_US.UTF-8
ENV LC_ALL     en_US.UTF-8
RUN apt-get install -y -q --no-install-recommends python-software-properties \
    software-properties-common && \
    add-apt-repository -y ppa:ondrej/php && \
    apt-get update && \
    apt-get install -y -q --no-install-recommends php7.0

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/local/bin/composer

# dependencies
RUN apt-get update && \
    apt-get install -y -q --no-install-recommends \
        libcairo2-dev \
        libjpeg8-dev \
        libpango1.0-dev \
	libgif-dev \
	build-essential \
	g++ \
        imagemagick \
	graphicsmagick \
	unzip \
   && rm -rf /var/lib/apt/lists/*

