FROM ubuntu:16.04

# Set debconf to run non-interactively
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

RUN locale-gen en_US.UTF-8
ENV LANG       en_US.UTF-8
ENV LC_ALL     en_US.UTF-8

COPY ./scripts/base.sh /build_scripts/base.sh
RUN /build_scripts/base.sh

COPY ./scripts/node_6.sh /build_scripts/node_6.sh
RUN /build_scripts/node_6.sh

COPY ./scripts/yarn.sh /build_scripts/yarn.sh
RUN /build_scripts/yarn.sh

COPY ./scripts/php7.0.sh /build_scripts/php7.0.sh
RUN /build_scripts/php7.0.sh

COPY ./scripts/composer.sh /build_scripts/composer.sh
RUN /build_scripts/composer.sh

COPY ./scripts/deps.sh /build_scripts/deps.sh
RUN /build_scripts/deps.sh
