FROM ubuntu:14.04

# Set debconf to run non-interactively
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# Install base dependencies
RUN apt-get update && apt-get install -y -q --no-install-recommends \
	git \
	ca-certificates \
        curl

# Install nvm with node and npm
RUN curl -sL https://deb.nodesource.com/setup_4.x | bash - \
    && apt-get install -y -q --no-install-recommends nodejs

# dependencies
RUN apt-get update && \
    apt-get install -y -q --no-install-recommends \
        libcairo2-dev \
        libjpeg8-dev \
        libpango1.0-dev \
	libgif-dev \
	build-essential \
	g++ \
        imagemagick \
	graphicsmagick \
   && rm -rf /var/lib/apt/lists/*

